includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Baseline.yaml
  - backbones/resnet18.yaml

classifier:
  name: Baseline
  kwargs:
    inner_param:
      inner_optim:
        name: Adam
        kwargs:
          lr: 1e-3
      inner_train_iter: 100
      inner_batch_size: 4
    feat_dim: 512
    num_class: 200

backbone:
  name: resnet18
  kwargs:
    is_flatten: True
    is_feature: False

# backbone:
#   name: resnet12
#   kwargs:
#     keep_prob: 0.0
#     avg_pool: True
#     is_flatten: True

# resnet12: feat_dim: 640

# resnet18: feat_dim: 512

# backbone:
#   name: WRN
#   kwargs:
#     depth: 28
#     widen_factor: 10

# WRN: feat_dim: 640
